# Generated by Django 5.1.4 on 2026-06-06 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('north_america', 'North America'), ('south_america', 'South America'), ('oceania', 'Oceania'), ('middle_east', 'Middle East')], db_index=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, help_text="e.g. 'Japanese Yen (¥)'", max_length=60)),
                ('visa_summary', models.TextField(blank=True, help_text='Short free-text summary of visa rules for common nationalities.')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('primary_category', models.CharField(choices=[('beach', 'Beach'), ('mountains', 'Mountains'), ('city', 'City'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('food', 'Food')], db_index=True, default='city', max_length=20)),
                ('budget_tier', models.PositiveSmallIntegerField(choices=[(1, '$ Budget'), (2, '$$ Mid-range'), (3, '$$$ Luxury')], db_index=True, default=2)),
                ('emoji', models.CharField(blank=True, help_text='Decorative glyph used in card placeholders.', max_length=8)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='destinations.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manually curated'), ('reddit', 'Reddit (PRAW)'), ('open_meteo', 'Open-Meteo API'), ('numbeo', 'Numbeo'), ('gov_advisory', 'Government travel advisory'), ('seed', 'Demo seed data')], default='manual', max_length=20)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this observation was captured from its source.')),
                ('month', models.PositiveSmallIntegerField(help_text='1 = January ... 12 = December')),
                ('avg_high_c', models.SmallIntegerField(help_text='Average daily high (°C).')),
                ('avg_low_c', models.SmallIntegerField(help_text='Average daily low (°C).')),
                ('rainfall_mm', models.PositiveSmallIntegerField(default=0)),
                ('climate_type', models.CharField(choices=[('warm_sunny', 'Warm & sunny'), ('hot_humid', 'Hot & humid'), ('mild', 'Mild'), ('cool_dry', 'Cool & dry'), ('cold', 'Cold')], default='mild', max_length=20)),
                ('is_recommended_month', models.BooleanField(default=False, help_text='Flagged as one of the better months to visit.')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='destinations.city')),
            ],
            options={
                'ordering': ['city', 'month'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manually curated'), ('reddit', 'Reddit (PRAW)'), ('open_meteo', 'Open-Meteo API'), ('numbeo', 'Numbeo'), ('gov_advisory', 'Government travel advisory'), ('seed', 'Demo seed data')], default='manual', max_length=20)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this observation was captured from its source.')),
                ('safety_score', models.PositiveSmallIntegerField(help_text='0-100; higher is safer.')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Exercise Caution'), (2, 'Moderate'), (3, 'Safe')], default=2)),
                ('health_notes', models.CharField(blank=True, max_length=255)),
                ('advisory_summary', models.CharField(blank=True, max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_advisories', to='destinations.city')),
            ],
            options={
                'verbose_name_plural': 'safety advisories',
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountains', 'Mountains'), ('city', 'City'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('food', 'Food')], max_length=20)),
                ('approx_price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate entry / participation price in EUR.', max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'category'], name='idx_activity_city_cat')],
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manually curated'), ('reddit', 'Reddit (PRAW)'), ('open_meteo', 'Open-Meteo API'), ('numbeo', 'Numbeo'), ('gov_advisory', 'Government travel advisory'), ('seed', 'Demo seed data')], default='manual', max_length=20)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this observation was captured from its source.')),
                ('daily_budget_eur', models.PositiveIntegerField(help_text='Daily cost for a budget traveller (EUR).')),
                ('daily_midrange_eur', models.PositiveIntegerField(help_text='Daily cost for a mid-range traveller (EUR).')),
                ('daily_luxury_eur', models.PositiveIntegerField(help_text='Daily cost for a luxury traveller (EUR).')),
                ('hostel_night_eur', models.PositiveIntegerField(default=0)),
                ('meal_cheap_eur', models.PositiveIntegerField(default=0)),
                ('local_transport_day_eur', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='destinations.city')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
                'indexes': [models.Index(fields=['city', '-captured_at'], name='idx_cost_city_recent')],
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['primary_category', 'budget_tier'], name='idx_city_cat_budget'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uniq_city_per_country'),
        ),
        migrations.AddIndex(
            model_name='monthlyweather',
            index=models.Index(fields=['city', 'month'], name='idx_weather_city_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyweather',
            constraint=models.UniqueConstraint(fields=('city', 'month'), name='uniq_weather_city_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyweather',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='weather_month_in_range'),
        ),
        migrations.AddIndex(
            model_name='safetyadvisory',
            index=models.Index(fields=['city', '-captured_at'], name='idx_safety_city_recent'),
        ),
        migrations.AddConstraint(
            model_name='safetyadvisory',
            constraint=models.CheckConstraint(condition=models.Q(('safety_score__gte', 0), ('safety_score__lte', 100)), name='safety_score_in_range'),
        ),
    ]
