# Generated by Django 5.1.15 on 2026-06-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='card_pill',
            field=models.CharField(blank=True, help_text="Optional editorial tag shown on Discover cards (e.g. 'Trending').", max_length=40),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.CharField(blank=True, help_text="Optional static image filename for the card (e.g. 'japan.png'), served from static/images/dest/. Presentation-only; falls back to the emoji placeholder when blank.", max_length=120),
        ),
    ]
