# Generated by Django 5.1.4 on 2026-06-06 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_budget_eur', models.PositiveIntegerField(default=100)),
                ('travel_month', models.PositiveSmallIntegerField(blank=True, help_text='1-12; null means flexible.', null=True)),
                ('preferred_climate', models.CharField(blank=True, max_length=20)),
                ('safety_priority', models.PositiveSmallIntegerField(default=3, help_text="1 (don't care) .. 5 (critical).")),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of ActivityCategory values.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CityAspectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('beach', 'Beach'), ('mountains', 'Mountains'), ('city', 'City'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('food', 'Food')], db_index=True, max_length=20)),
                ('score', models.PositiveSmallIntegerField(help_text='0-100 sentiment score for this aspect.')),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='Number of reviews the score was derived from.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_scores', to='destinations.city')),
            ],
            options={
                'ordering': ['city', 'aspect'],
                'indexes': [models.Index(fields=['city', 'aspect'], name='idx_aspect_city')],
                'constraints': [models.UniqueConstraint(fields=('city', 'aspect'), name='uniq_aspect_per_city'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='aspect_score_in_range')],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('score_at_save', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='destinations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'city'), name='uniq_saved_city_per_user')],
            },
        ),
    ]
